name: Clang Format Check
on: [push, pull_request]  # 推送/拉取请求时触发

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: sudo apt install clang-format -y

      - name: Check code style
        run: |
          find . -name "*.h" -o -name "*.hpp" -o -name "*.cpp" | xargs clang-format --dry-run --Werror
