name: Clang Format Check
on: #:push, pull_request]  # 推送/拉取请求时触发
    workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: sudo apt install clang-format -y

      - name: Check code style
        run: |
          echo "third_party/\n" >> .clang-format-ignore
          echo "pb/\n" >> .clang-format-ignore
          find ./public/cpp -name "*.h" -o -name "*.hpp" -o -name "*.cpp"
          find ./public/cpp -name "*.h" -o -name "*.hpp" -o -name "*.cpp" | xargs clang-format --dry-run --Werror
