name: Clang Format Check
on: #:push, pull_request]  # 推送/拉取请求时触发
    workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: sudo apt install clang-format -y

      - name: Check code style
        run: |
          #find ./public/cpp \( -path "*/third_party" -o -path "*/pb" \) -prune -o \( -name "*.h" -o -name "*.hpp" -o -name "*.cpp" \) -type f
          #find ./public/cpp \( -path "*/third_party" -o -path "*/pb" \) -prune -o \( -name "*.h" -o -name "*.hpp" -o -name "*.cpp" \) -type f | xargs clang-format --dry-run --Werror
          xargs clang-format --dry-run --Werror ./public/cpp/actor/actor_base/actor.cpp
